# Generated by Django 5.2.17 on 2026-10-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoAnalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('tipo_detectado', models.CharField(max_length=50)),
                ('mime', models.CharField(blank=True, max_length=100)),
                ('tamano', models.PositiveBigIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
